import { Product, Service } from '@/types';

export const MOCK_PRODUCTS: Product[] = [
  // Rações
  {
    id: 'rac-1',
    name: 'Ração Golden Special Cães Adultos - Frango & Carne (15kg)',
    description: 'Nutrição completa e balanceada para cães adultos, desenvolvida com ingredientes selecionados, sem corantes e aromatizantes artificiais.',
    price: 169.90,
    image_url: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600&auto=format&fit=crop&q=80',
    category: 'racoes',
    rating: 4.7,
    reviews_count: 142,
    in_stock: true,
    is_featured: true,
  },
  {
    id: 'rac-2',
    name: 'Ração Premier Cães Adultos Raças Pequenas - Frango & Salmão (12kg)',
    description: 'Alimento super premium indicado para cães adultos de pequeno porte. Grãos em tamanho ideal para facilitar a mastigação.',
    price: 219.90,
    image_url: 'https://images.unsplash.com/photo-1608454367599-c11394f0e0df?w=600&auto=format&fit=crop&q=80',
    category: 'racoes',
    rating: 4.9,
    reviews_count: 98,
    in_stock: true,
    is_featured: true,
  },
  {
    id: 'rac-3',
    name: 'Ração Royal Canin Golden Retriever Adulto (12kg)',
    description: 'Alimento super premium completo sob medida para cães da raça Golden Retriever a partir dos 15 meses de idade. Auxilia na saúde cardíaca.',
    price: 389.90,
    image_url: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=800&auto=format&fit=crop&q=80',
    category: 'racoes',
    rating: 4.8,
    reviews_count: 57,
    in_stock: true,
    is_featured: true,
  },
  {
    id: 'rac-4',
    name: 'Ração GranPlus Choice Cães Adultos - Ovelha & Arroz (15kg)',
    description: 'Alimento de alta qualidade que proporciona aos cães adultos todos os nutrientes necessários para uma vida saudável e ativa.',
    price: 149.90,
    image_url: 'https://images.unsplash.com/photo-1569591159212-b02ea8a9f239?w=600&auto=format&fit=crop&q=80',
    category: 'racoes',
    rating: 4.5,
    reviews_count: 82,
    in_stock: true,
    is_featured: false,
  },

  // Acessórios
  {
    id: 'ace-1',
    name: 'Coleira Ajustável Premium Refletiva - Preta',
    description: 'Coleira de nylon de alta resistência com costura refletiva para dar segurança máxima ao seu cão em passeios noturnos.',
    price: 39.90,
    image_url: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&auto=format&fit=crop&q=80',
    category: 'acessorios',
    rating: 4.6,
    reviews_count: 34,
    in_stock: true,
    is_featured: false,
  },
  {
    id: 'ace-2',
    name: 'Guia Retrátil para Cães Premium - 5 metros',
    description: 'Cabo de fita super resistente com sistema de freio inteligente e gatilho ergonômico para um passeio livre e seguro.',
    price: 79.90,
    image_url: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&auto=format&fit=crop&q=80',
    category: 'acessorios',
    rating: 4.7,
    reviews_count: 67,
    in_stock: true,
    is_featured: true,
  },
  {
    id: 'ace-3',
    name: 'Cama Pet Nuvem Ortopédica Luxo - Tamanho G',
    description: 'Confeccionada com material ultra macio em formato circular com bordas elevadas que aliviam dores articulares e estresse.',
    price: 189.90,
    image_url: 'https://images.unsplash.com/photo-1541599540903-216a46ca1ad0?w=600&auto=format&fit=crop&q=80',
    category: 'acessorios',
    rating: 4.9,
    reviews_count: 112,
    in_stock: true,
    is_featured: true,
  },
  {
    id: 'ace-4',
    name: 'Comedouro Elevado Ergonômico de Inox & Madeira',
    description: 'Suporte elevado em bambu com tigela de inox. Melhora a digestão e reduz a tensão no pescoço e articulações do pet.',
    price: 119.90,
    image_url: 'https://images.unsplash.com/photo-1615678815958-5910c6811c25?w=600&auto=format&fit=crop&q=80',
    category: 'acessorios',
    rating: 4.5,
    reviews_count: 28,
    in_stock: true,
    is_featured: false,
  },

  // Banho e Tosa
  {
    id: 'bt-1',
    name: 'Shampoo Neutro Hipoalergênico Pet - 500ml',
    description: 'Formulado com ativos naturais como camomila e aloe vera. Limpa suavemente a pelagem respeitando o pH natural da pele do pet.',
    price: 42.90,
    image_url: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=600&auto=format&fit=crop&q=80',
    category: 'banho-e-tosa',
    rating: 4.8,
    reviews_count: 94,
    in_stock: true,
    is_featured: true,
  },
  {
    id: 'bt-2',
    name: 'Condicionador Hidratante Pet Camomila - 500ml',
    description: 'Promove brilho e maciez intensa. Facilita o desembaraço de nós e deixa um perfume suave e agradável após o banho.',
    price: 45.90,
    image_url: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=600&auto=format&fit=crop&q=80',
    category: 'banho-e-tosa',
    rating: 4.6,
    reviews_count: 51,
    in_stock: true,
    is_featured: false,
  },
  {
    id: 'bt-3',
    name: 'Escova Rasqueadeira de Cerdas Macias Autolimpante',
    description: 'Remove pelos mortos e sujeira com cerdas em ângulo de proteção. Mecanismo traseiro ejeta os pelos de forma fácil.',
    price: 54.90,
    image_url: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=600&auto=format&fit=crop&q=80',
    category: 'banho-e-tosa',
    rating: 4.7,
    reviews_count: 48,
    in_stock: true,
    is_featured: false,
  },
  {
    id: 'bt-4',
    name: 'Cortador de Unhas Pet Profissional com Trava',
    description: 'Lâminas afiadas de aço inox com limitador de segurança e trava de fechamento para evitar cortes profundos e acidentes.',
    price: 34.90,
    image_url: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=600&auto=format&fit=crop&q=80',
    category: 'banho-e-tosa',
    rating: 4.7,
    reviews_count: 22,
    in_stock: true,
    is_featured: false,
  },
];

export const MOCK_SERVICES: Service[] = [
  {
    id: 'serv-1',
    name: 'Banho Clássico',
    description: 'Inclui higienização completa dos pelos, limpeza de ouvidos, corte de unhas e perfume suave adequado para pets.',
    price: 65.00,
    duration: '45 min',
    icon: 'Droplets',
  },
  {
    id: 'serv-2',
    name: 'Banho & Tosa Higiênica',
    description: 'Banho clássico somado à tosa das patinhas, barriga e regiões íntimas para manter o conforto e higiene no dia a dia.',
    price: 95.00,
    duration: '1h 15min',
    icon: 'Scissors',
  },
  {
    id: 'serv-3',
    name: 'Tosa da Raça (Máquina ou Tesoura)',
    description: 'Serviço completo de banho combinado com estilização específica conforme o padrão oficial da raça ou preferência do tutor.',
    price: 130.00,
    duration: '2h',
    icon: 'Sparkles',
  },
];
