import { Product, Service } from '@/types';

export const MOCK_PRODUCTS: Product[] = [
  // Rações
  {
    id: 'rac-1',
    name: 'Ração Premium Cães Adultos - Frango & Arroz',
    description: 'Nutrição 100% completa e balanceada para cães adultos de médio e grande porte. Auxilia na saúde da pele e pelos brilhantes.',
    price: 189.90,
    originalPrice: 219.90,
    image_url: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600&auto=format&fit=crop&q=80',
    category: 'racoes',
    rating: 4.8,
    reviews_count: 124,
    in_stock: true,
    is_featured: true,
  },
  {
    id: 'rac-2',
    name: 'Ração Seca Premium Gatos Castrados - Salmão',
    description: 'Fórmula exclusiva com controle de pH urinário e calorias reduzidas para manter o peso saudável de gatos adultos castrados.',
    price: 154.90,
    image_url: 'https://images.unsplash.com/photo-1569591159212-b02ea8a9f239?w=600&auto=format&fit=crop&q=80',
    category: 'racoes',
    rating: 4.9,
    reviews_count: 89,
    in_stock: true,
    is_featured: true,
  },
  {
    id: 'rac-3',
    name: 'Ração Super Premium Filhotes - Raças Pequenas',
    description: 'Enriquecida com DHA para desenvolvimento cerebral saudável e grãos adequados ao tamanho do maxilar de filhotes de raças pequenas.',
    price: 98.50,
    originalPrice: 110.00,
    image_url: 'https://images.unsplash.com/photo-1608454367599-c11394f0e0df?w=600&auto=format&fit=crop&q=80',
    category: 'racoes',
    rating: 4.7,
    reviews_count: 45,
    in_stock: true,
    is_featured: false,
  },

  // Acessórios
  {
    id: 'ace-1',
    name: 'Guia Retrátil Premium - 5 Metros',
    description: 'Fita de nylon super resistente e ergonômica com sistema de freio inteligente para dar liberdade com total segurança no passeio.',
    price: 79.90,
    image_url: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&auto=format&fit=crop&q=80',
    category: 'acessorios',
    rating: 4.6,
    reviews_count: 67,
    in_stock: true,
    is_featured: true,
  },
  {
    id: 'ace-2',
    name: 'Cama Ortopédica Nuvem Luxo - Tamanho G',
    description: 'Confeccionada com espuma viscoelástica de alta densidade e tecido térmico ultra macio. Hipoalergênica e lavável.',
    price: 249.90,
    originalPrice: 289.00,
    image_url: 'https://images.unsplash.com/photo-1541599540903-216a46ca1ad0?w=600&auto=format&fit=crop&q=80',
    category: 'acessorios',
    rating: 5.0,
    reviews_count: 112,
    in_stock: true,
    is_featured: true,
  },
  {
    id: 'ace-3',
    name: 'Comedouro Duplo Elevado de Inox & Bambu',
    description: 'Design moderno e ergonômico que previne refluxo e problemas digestivos. Taças removíveis em inox fáceis de limpar.',
    price: 129.00,
    image_url: 'https://images.unsplash.com/photo-1615678815958-5910c6811c25?w=600&auto=format&fit=crop&q=80',
    category: 'acessorios',
    rating: 4.5,
    reviews_count: 38,
    in_stock: true,
    is_featured: false,
  },

  // Banho e Tosa (Acessórios/Produtos Relacionados)
  {
    id: 'bt-1',
    name: 'Shampoo Neutro Hipoalergênico Pet - 500ml',
    description: 'Formulado com extrato natural de camomila e aloe vera. Limpa suavemente respeitando o pH natural da pele do pet.',
    price: 42.90,
    originalPrice: 49.90,
    image_url: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=600&auto=format&fit=crop&q=80',
    category: 'banho-e-tosa',
    rating: 4.8,
    reviews_count: 94,
    in_stock: true,
    is_featured: true,
  },
  {
    id: 'bt-2',
    name: 'Escova Rasqueadeira Autolimpante',
    description: 'Remove pelos mortos e nós sem machucar. Mecanismo inovador que ejeta os pelos acumulados com apenas um clique.',
    price: 59.90,
    image_url: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=600&auto=format&fit=crop&q=80',
    category: 'banho-e-tosa',
    rating: 4.7,
    reviews_count: 53,
    in_stock: true,
    is_featured: false,
  },
];

export const MOCK_SERVICES: Service[] = [
  {
    id: 'serv-1',
    name: 'Banho Clássico',
    description: 'Inclui higienização completa dos pelos, limpeza de ouvidos, corte de unhas e perfume suave adequado para pets.',
    price: 65.00,
    duration: '45 min',
    icon: 'Droplets',
  },
  {
    id: 'serv-2',
    name: 'Banho & Tosa Higiênica',
    description: 'Banho clássico somado à tosa das patinhas, barriga e regiões íntimas para manter o conforto e higiene no dia a dia.',
    price: 95.00,
    duration: '1h 15min',
    icon: 'Scissors',
  },
  {
    id: 'serv-3',
    name: 'Tosa da Raça (Máquina ou Tesoura)',
    description: 'Serviço completo de banho combinado com estilização específica conforme o padrão oficial da raça ou preferência do tutor.',
    price: 130.00,
    duration: '2h',
    icon: 'Sparkles',
  },
];
